name: .NET

on:
  push:
    branches: [ feature/featurename ]
  pull_request:
    branches: [ feature/featurename ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Bash Command Lines for GitHub Actions
      # You may pin to the exact commit or the version.
      # uses: jdickey/bash@bc09809bde62634bf1f6fdfc820428e7ac10eea4
      uses: jdickey/bash@v.1.1.1
